version: "2.0"
services:
  db:
    restart: always
    image: mysql:5.7

    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: hotspot.com
      MYSQL_DATABASE: bookinn_development
      MYSQL_USER: user
      MYSQL_PASSWORD: hotspot.com

    ports:
      - "3307:3307"

    volumes:
      - ./tmp/db:/var/lib/mysql/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: bookinn_development
      DB_PASSWORD: hotspot.com
      DB_HOST: db